spring.application.name=cru-demo
spring.datasource.url=jdbc:h2:mem:cruapp;MODE=LEGACY;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=true
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
